Website = "https://github.com/heathcliff26/infraspace-savegame-editor"

[Details]
Icon = "packages/io.github.heathcliff26.infraspace-savegame-editor.png"
Name = "InfraSpace Savegame Editor"
ID = "com.github.heathcliff26.infraspace-savegame-editor"
Version = "1.3.6"
Build = 1

[Migrations]
fyneDo = true
